### PR TITLE
Changes and notes to improve reproducibility.

### PR DESCRIPTION
**Pull request by fperez**
Adds both environment.yml and requirements.txt files to help recreate a reproducible environment to run the main notebook, a Makefile, and a few changes to the code itself (such as setting random seeds manually).

The version of the notebook committed here differs in small ways from the original, since it's impossible to perfectly recreate that (random seeds were not saved).  But there are no substantive changes to any of the results, and this updated version should be as reasonably stable as possible, given the limitations of the library versions used at the time (such as matplotlib 1.5.0 embedding timestamps into PDFs).

### CODE REVIEW

**Comment by fperez** [comment]
BTW, this is 100% orthogonal to @tacaswell's #1, so you can merge them in either order.

Thanks again for your gracious response!  I had a chance to use this as an illustration of best practices in open science during my keynote yesterday at the [Data Dialogs](https://datadialogs.ischool.berkeley.edu/2017) conference at UC Berkeley :)

I hope this is useful. I certainly learned a lot!

**Comment by benlaken** [comment]
Thanks again Fernando - that was a big help! :+1:

**Comment by fperez** [comment]
Thanks for merging! It will be great to close this loop with my class tomorrow, they completed the project last week and this is an excellent way to illustrate the power of open, collaborative science, which is the whole point of the course.

Looking forward to meeting you if we have a chance to cross paths in the scientific python research/conference circuit!

**Comment by benlaken** [comment]
No problem; thanks again for improving the repo. Very happy to hear that the work has been of use to people. And yes, likewise I look forward to running into you in the future on the conference circuit!

**Pull request merged**
